services:
  # Mac環境用 platform指定
  db:
    platform: linux/x86_64

  php:
    platform: linux/x86_64

  phpmyadmin:
    platform: linux/x86_64

  mail:
    platform: linux/x86_64

  frontend:
    platform: linux/x86_64
